### ISSUE TITLE
Custom field MembershipNo not working after change in DB table

### ISSUE THREAD

**Issue by wintermoor** [Project60/org.project60.membership#52]
Tested this extension with success in 5.37.2 on WordPress 5.8. Extension rev. neither 0.7-alpha5 nor 0.6.2. 

Then I deleted all membership-related custom fields and the civicrm_membership_log table to change the civicrm_membership table: my aim was to manually change the membership id from this new install to membership id from real life. Next step was to create new custom fields for mid & cancellation date. But this time I was unable to show the mid up on the contact under the external ID. 

Is there a dependency to civicrm_membership_log table?

**Comment by bjendres** [comment]
Hi @wintermoor.

While I'm not quite clear what exactly you did, I have a couple of questions/comments:

This extension allows you to create a custom field in a membership custom group for a membership number, which the CiviCRM core lacks, and then configure the extension so that:
1. this membership number is automatically generated for new memberships
2. the membership number is displayed in the summary view
3. the membership number is available as a token

If you can't use your old custom fields for some reason, you should be able to create a new one and copy the data from your field there.

> my aim was to manually change the membership id from this new install to membership id from real life

When you're saying the "membership id" I hope you are not referring to the ``civicrm_membership.id`` column, right?!

> I deleted [...] the civicrm_membership_log table. [...] Is there a dependency to civicrm_membership_log table?

Since this is a CiviCRM core table, I hope you didn't ``DROP`` the ``civicrm_membership_log`` table. This would most likely cause trouble with the system.

> I deleted all membership-related custom fields

Since it's hard know which and where custom fields are referenced in the system, I usually simply disable them to save you trouble.

**Comment by wintermoor** [comment]
Hi @bjendres , yes, I messed this up and fixed it now. No more questions :) 
Thank you. 
Sonnige Grüße
